# -*- coding: utf-8 -*-
"""
Created on Wed Oct  2 12:14:56 2024

@author: zacht

Localized script to generate neutron spectra using the FRUIT algorithm
 developed by James McGreivy (https://scholar.afit.edu/facpub/1278/).
 
ALGORITHM:                                              VARIABLE        SHAPE
    0. Import modules
    1. Define Functions
    2. User Function Output
"""
###############################################################################
# 0. Import modules                                                           #
###############################################################################
import numpy as np
import constants
import random

# Custom Python libraries
import fruit_spectra

###############################################################################
# 1. Define Functions                                                         #
###############################################################################
# FRUIT Algorithm
def FRUIT_spectra_algorithm(NUM_DATA = 2):

    yData = []
    for i in range(NUM_DATA):
        spectra_type = random.randint(0, 3)

        if spectra_type == 0:
            yData.append(fruit_spectra.randFission())
        elif spectra_type == 1:
            yData.append(fruit_spectra.randEvap())
        elif spectra_type == 2:
            yData.append(fruit_spectra.randGauss())
        else:
            yData.append(fruit_spectra.randHighEnergy())

    yData = np.array(yData)

    return yData

###############################################################################
# 1. User Function Output                                                     #
###############################################################################
# After running this file, any number of spectra can be generated by typing in:
    # "FRUIT(X)" and X will be the number of spectra you want. Then I dumped it
# into a csv file in the command line.

FRUIT = lambda num_data : FRUIT_spectra_algorithm(num_data)

